### ISSUE TITLE
How to declare insert, update and remove methods for a model?

### ISSUE THREAD

**Issue by hervejegou** [coniel/meteor-base-model#1]
I would like to use meteor methods so I am trying to replace socialize:base-model with this improved base-model.

But I am not sure how to define the meteor methods for insert, update and save for each model created with this. Could you give me (or add to read me?) a quick example? The rest is clear and works.

Thanks for your help.

**Comment by coniel** [comment]
Hey, good point, I totally forgot to add that to the readme.

I'll try add it as soon as I can, for now just have a look at my other packages which use BaseModel, e.g. the post model in the postable package: https://github.com/coniel/meteor-postable/blob/master/common/post-model.js#L49

You can read more about validated methods here: https://github.com/meteor/validated-method

The post model uses the [loggedin mixin](https://atmospherejs.com/tunifight/loggedin-mixin) (only logged in users are allowed to post) and all methods should use the [callpromise mixin](https://atmospherejs.com/didericis/callpromise-mixin) as the BaseModel expects them to be using it.

Since it uses promises, you handle callbacks a bit differently. e.g:

```
var post = new Post({body: "Hello everyone!"});

post.save().then((result) => {
    // handle success
}).catch((error) => {
   // handle error
});
```

The methods might look a bit scary at first but once you understand what's going on they are quick to write up (at some point I might try and improve the BaseModel so that it provides a faster way to define the methods since there is a lot of repetition).

Let me know if you have any questions, I'll try and add a detailed section to the readme this week.

**Comment by hervejegou** [comment]
Thanks the post model is a good example for validated methods. I will try to use that for now.
